---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r Install}
install.packages("rpart")
install.packages("rpart.plot")
install.packages("rattle")
install.packages("RColorBrewer")
```

```{r Library}
library(tidyverse)
library(tidymodels)
library(caret)
library(rpart)
library(rpart.plot)
library(RColorBrewer)
library(skimr)
library(rattle)
```

```{r Read in}
library(readr)
disease <- read_csv("heart_disease-1.csv")
View(disease)
```

```{r convert}
disease = disease %>%
  mutate(Sex = as_factor(Sex)) %>%
  mutate(ChestPainType = as_factor(ChestPainType)) %>%
  mutate(RestingECG = as_factor(RestingECG)) %>%
  mutate(ExerciseAngina = as_factor(ExerciseAngina)) %>%
  mutate(ST_Slope = as_factor(ST_Slope)) %>%
  mutate(HeartDisease = as_factor(HeartDisease)) %>%
  mutate(HeartDisease = fct_recode(HeartDisease, "No" = "0", "Yes" = "1"))

str(disease)
skim(disease)
```

```{r}

set.seed(12345)
disease_split = initial_split(disease, prop = 0.7, strata = HeartDisease)
train = training(disease_split)
test = testing(disease_split)

```

```{r}
disease_recipe = recipe(HeartDisease ~ Age + Sex + ChestPainType + RestingBP + Cholesterol + FastingBS + RestingECG + MaxHR + ExerciseAngina + Oldpeak + ST_Slope, train)

tree_model = decision_tree() %>%
  set_engine("rpart", model = TRUE) %>%
  set_mode("classification")

disease_wflow = 
  workflow() %>%
  add_model(tree_model) %>%
  add_recipe(disease_recipe)

disease_fit = fit(disease_wflow, train)
```

```{r}

disease_fit %>%
  pull_workflow_fit() %>%
  pluck("fit")
tree = disease_fit %>%
  pull_workflow_fit() %>%
  pluck("fit")

rpart.plot(tree)

disease_fit$fit$fit$fit$cptable
```

```{r Tuning Grid}

set.seed(123)
folds = vfold_cv(train, v = 5)

disease_recipe = recipe(HeartDisease ~., train) %>%
  step_dummy(all_nominal(), -all_outcomes())

tree_model = decision_tree(cost_complexity = tune()) %>%
  set_engine("rpart", model = TRUE) %>%
  set_mode("classification")

tree_grid = grid_regular(cost_complexity(),
                         levels = 25)
disease_wflow = 
  workflow() %>%
  add_model(tree_model) %>%
  add_recipe(disease_recipe)

tree_res = 
  disease_wflow %>%
  tune_grid(
    resamples = folds,
    grid = tree_grid
  )

tree_res

```

```{r}
tree_res %>%
  collect_metrics() %>%
  ggplot(aes(cost_complexity, mean)) +
  geom_line(size = 1.5, alpha = 0.6) +
  geom_point(size = 2) +
  facet_wrap(~ .metric,scales = "free", nrow = 2)

```

```{r}
best_tree = tree_res %>%
  select_best(metric = "accuracy")
best_tree
```

```{r Finalize}
final_wf = disease_wflow %>%
  finalize_workflow(best_tree)

final_fit = fit(final_wf, train)

tree = final_fit %>%
  pull_workflow_fit() %>%
  pluck("fit")

rpart.plot(tree)
```

```{r}
```


```{r}
treepred = predict(final_fit, train, type = "class")

confusionMatrix(treepred$.pred_class,train$HeartDisease,positive = "Yes")

```

```{r}
treepred1 = predict(final_fit, test, type = "class")

confusionMatrix(treepred1$.pred_class,test$HeartDisease,positive = "Yes")
```


```

